quarkus:
  profile: prod

#"%dev":
#  quarkus:
#    application:
#    name: my-quarkus-demo
#    http:
#      port: 8888
#      test-port: 8889
#  greeting:
#    group:
#      name: greetingGroupName
#      age: 10
#
#"%prod":
#  quarkus:
#    application:
#    name: my-quarkus-demo
#    http:
#      port: 8888
#      test-port: 8889
#  greeting:
#    group:
#      name: greetingGroupName
#      age: 10

